require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 3.0.1
  Exclude:
    - db/**/*
    - bin/**/*
    - vendor/**/*
    - tmp/**/*

Style/Documentation:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Layout/LineLength:
  Max: 120

RSpec/ExampleLength:
  Max: 10

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleExpectations:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - config/**/*

Metrics/ModuleLength:
  Exclude:
    - spec/**/*
